<?php

/**
 * Implements hook_entity_extra_field_info().
 */
function pseudofields_entity_extra_field_info() {
  $extra['node']['article']['display']['foo_bar'] = [
    'label'       => t('My pseudo field'),
    'description' => t('My pseudo field description.'),
    'weight'      => 0,
    'visible'     => TRUE,
  ];
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function pseudofields_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('foo_bar')) {
    $build['foo_bar'] = [
      '#markup' => 'This is my custom content',
    ];
  }
}
