<?php

/**
 * Implements hook_field_extra_fields().
 */
function pseudofields_field_extra_fields() {
  $extra['node']['article']['display']['foo_bar'] = [
    'label'       => t('My pseudo field'),
    'description' => t('My pseudo field description.'),
    'weight'      => 0,
    'visible'     => TRUE,
  ];
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function pseudofields_node_view($node, $view_mode, $langcode) {
  // Get all extra fields for current node.
  $extra_fields = field_info_extra_fields('node', $node->type, 'display');
  // Managed by display mode configuration.
  if (!empty($extra_fields['foo_bar']['display'][$view_mode]['visible'])) {
    $node->content['foo_bar'] = [
      '#markup' => 'This is my custom content',
    ];
  }
}
